#### AUTOMESSAGE ####
Messages:
- '&8[&4&lARE&c&lHARD&8] &8>> &7Nasz serwer glosowy teamspeak3: &carehard.pl'
- '&8[&4&lARE&c&lHARD&8] &8>> &7Nasza strona internetowa: &cwww.arehard.pl'
- '&8[&4&lARE&c&lHARD&8] &8>> &7Masz jakis pomysl co mozna dodac na serwer? /zglos'
- '&8[&4&lARE&c&lHARD&8] &8>> &7Wiecej informacji na temat rangi &6vip pod &c/vip'
- '&8[&4&lARE&c&lHARD&8] &8>> &7Wiecej informacji na tmeat rangi &5sponsor pod &c/sponsor'
- '&8[&4&lARE&c&lHARD&8] &8>> &7Nasz Fanpage: &cwww.fb.com/arehardpl'
#### INFO ####
message:
  pomoc:
    - "test"
  sponsor:
    - "test"
  vip:
    - "test"