name: AreHard_PVP
authors: [adrianekk, Piechuuu]
version: 1.0
main: net.arehard.core.Main

commands:
  is:
    aliases: [itemshop]
  alert:
  gm:
    aliases: [gamemode]
  fly:
  chat:
  kick:
  ban:
  coins:
  acoins:
  alert:
  setspawn:
  spawn:
  vanish:
    aliases: [v]
  yt:
 